#' Psych-DS App UI
#'
#' This file defines the main UI for the Psych-DS app.
#' It loads the modular UI components and handles the top-level UI structure.

# Load UI modules
source("modules/ui_modules.R")

# Main UI definition
ui <- dashboardPage(
  skin = "blue",

  # Header
  dashboardHeader(
    title = span("psych-DS", style = "font-size: 24px;"),
    titleWidth = 200
  ),

  # Sidebar with fixed width
  dashboardSidebar(
    width = 200,
    sidebarMenu(
      id = "sidebar",
      menuItem("Create Dataset", tabName = "create", icon = icon("plus-circle"), selected = TRUE),
      menuItem("Validate Dataset", tabName = "validate", icon = icon("check-circle")),
      menuItem("Update Dictionary", tabName = "dictionary", icon = icon("book")),
      menuItem("Dataset Explorer", tabName = "explorer", icon = icon("table")),
      menuItem("Upload to OSF", tabName = "upload", icon = icon("cloud-upload")),
      menuItem("Help", tabName = "help", icon = icon("question-circle"))
    )
  ),

  # Body
  dashboardBody(
    useShinyjs(),

    # External resources
    tags$head(
      # Include the external CSS file with cache-busting
      tags$link(rel = "stylesheet", type = "text/css", 
               href = paste0("css/styles.css?v=", format(Sys.time(), "%Y%m%d%H%M%S"))),
      
      # Include SortableJS library for drag-and-drop functionality
      tags$script(src = "https://cdn.jsdelivr.net/npm/sortablejs@1.14.0/Sortable.min.js"),
      
      # Include EventEmitter for validator event handling
      tags$script(src = "https://cdn.jsdelivr.net/npm/eventemitter3@4.0.7/umd/eventemitter3.min.js"),
      
      # Include jsonld library for validation
      tags$script(src = "js/jsonld.min.js"),

      # Include the validator.js module
      tags$script(src = "js/validator.js", type = "module"),
      

      tags$script(src = "js/validator-utils.js"),
    ),

    # JavaScript handlers for UI interactions
    
    #' UI refresh handler - forces redraw of UI elements
    #' Used when dynamic elements need to be refreshed
    tags$script(HTML("
      Shiny.addCustomMessageHandler('refreshUI', function(message) {
        // Force a redraw by slightly resizing elements
        $('.step-circle').each(function() {
          var $this = $(this);
          var w = $this.width();
          $this.width(w+1);
          setTimeout(function() { $this.width(w); }, 50);
        });
      });
    ")),

    tags$script(HTML("
      Shiny.addCustomMessageHandler('scrollToElement', function(message) {
        var element = document.getElementById(message.elementId);
        if (element) {
          element.scrollIntoView({
            behavior: 'smooth',
            block: 'center'
          });
        }
      });
    ")),
    
    #' File download handler - allows downloading files generated by the app
    tags$script(HTML("
      Shiny.addCustomMessageHandler('downloadFile', function(message) {
        var link = document.createElement('a');
        link.href = window.URL.createObjectURL(new Blob([message.filepath]));
        link.download = message.filename;
        link.click();
      });
    ")),
    
    #' Tab change handler - allows programmatically changing tabs
    tags$script(HTML("
      Shiny.addCustomMessageHandler('changeTab', function(message) {
        // Find the sidebar menu item and trigger a click
        var tabItem = $('.sidebar-menu a[data-value=\"' + message.tabName + '\"]');
        if (tabItem.length) {
          tabItem.click();
        }
      });
      Shiny.addCustomMessageHandler('scrollToTop', function(message) {
        window.scrollTo({top: 0, behavior: 'smooth'});
      });
    ")),

    # Application tab items
    tabItems(
      # Create Dataset Tab
      tabItem(
        tabName = "create",
        uiOutput("create_dataset_ui")
      ),

      # Validate Dataset Tab
      tabItem(
        tabName = "validate",
        validateUI("validate_dataset")
      ),

      # Update Dictionary Tab
      tabItem(
        tabName = "dictionary",
        dataDictionaryUI("data_dictionary")
      ),

      # Dataset Explorer Tab
      tabItem(
        tabName = "explorer",
        datasetExplorerUI("dataset_explorer")
      ),

      # Upload to OSF Tab
      tabItem(
        tabName = "upload",
        h2("Upload to OSF"),
        p("This feature will allow you to upload Psych-DS datasets to the Open Science Framework (OSF)."),
        div(
          class = "section-box",
          div(class = "section-title", "Select Dataset"),
          div(class = "section-description",
              "Select a Psych-DS dataset to upload to OSF."),

          div(
            class = "directory-input",
            textInput(
              "upload_dir",
              label = NULL,
              value = "",
              placeholder = "Path to Psych-DS dataset",
              width = "100%"
            ),
            shinyDirButton(
              "upload_dir_select",
              label = "...",
              title = "Select a dataset directory",
              class = "browse-btn"
            )
          ),

          div(
            class = "section-title",
            style = "margin-top: 20px;",
            "OSF Project"
          ),
          div(class = "section-description",
              "Enter your OSF project information."),

          textInput("osf_project", "Project ID", placeholder = "OSF project ID"),
          passwordInput("osf_token", "OSF Token", placeholder = "Your OSF personal access token"),

          div(
            style = "text-align: right; margin-top: 20px;",
            actionButton(
              "upload_btn",
              "Upload",
              class = "continue-btn"
            )
          )
        )
      ),

      # Help Tab
      tabItem(
        tabName = "help",
        h2("Help"),
        div(
          class = "section-box",
          div(class = "section-title", "About Psych-DS"),
          p("The Psych-DS standard is a data organization standard for psychological datasets.
            It defines a consistent structure for organizing research data, making it easier to
            share, understand, and reuse psychological datasets."),

          div(class = "section-title", style = "margin-top: 20px;", "Using This App"),
          p("This app provides tools for creating, validating, and exploring Psych-DS datasets:"),
          tags$ul(
            tags$li(strong("Create Dataset:"), "Convert existing data to the Psych-DS format with a step-by-step interface"),
            tags$li(strong("Validate Dataset:"), "Check if datasets comply with the Psych-DS standard"),
            tags$li(strong("Update Dictionary:"), "Create and edit data dictionaries for your datasets"),
            tags$li(strong("Dataset Explorer:"), "Explore the structure and content of Psych-DS datasets"),
            tags$li(strong("Upload to OSF:"), "Upload Psych-DS datasets to the Open Science Framework (OSF)")
          ),

          div(class = "section-title", style = "margin-top: 20px;", "Resources"),
          p("For more information about the Psych-DS standard, visit the following resources:"),
          tags$ul(
            tags$li(tags$a(href = "https://psych-ds.github.io/", "Psych-DS Website", target = "_blank")),
            tags$li(tags$a(href = "https://github.com/psych-ds/psych-DS", "Psych-DS GitHub Repository", target = "_blank"))
          )
        )
      )
    )
  )
)